tasks:
  - name: Run Composer
    init: |
      sudo ln -s /etc/php/8.2/mods-available/sqlsrv.ini /etc/php/8.2/cli/conf.d/20-sqlsrv.ini
      sudo ln -s /etc/php/8.2/mods-available/pdo_sqlsrv.ini /etc/php/8.2/cli/conf.d/30-pdo_sqlsrv.ini
      sudo ln -s /etc/php/8.2/mods-available/oci8.ini /etc/php/8.2/cli/conf.d/20-oci8.ini
      echo oci8.privileged_connect=1 | sudo tee -a /etc/php/8.2/mods-available/oci8.ini

    command: |
      composer install
      docker compose -f docker-compose.yml up -d

image: byjg/gitpod-image:full

jetbrains:
  phpstorm:
    vmoptions: '-Xmx4g'
  plugins:
    - com.github.copilot
    - com.intellij.kubernetes
    - com.intellij.mermaid
    - ru.adelf.idea.dotenv
    - org.toml.lang

vscode:
  extensions:
    - ikappas.composer
    - hbenl.test-adapter-converter
    - hbenl.vscode-test-explorer
    - felixfbecker.php-debug
    - neilbrayfield.php-docblocker
    - bmewburn.vscode-intelephense-client
    - getpsalm.psalm-vscode-plugin
    - SonarSource.sonarlint-vscode
    - recca0120.vscode-phpunit
