language: php
php:
  - "7.3"
  - "7.2"
  - "7.1"
  - "7.0"
  - "5.6"


services:
  - docker

before_install:
  - sudo service mysql stop || echo "mysql not stopped"
  - sudo service postgresql stop || echo "postgresql not stopped"
  - docker-compose up -d postgres mysql

install:
  - php -i
  - composer install

script: 
  - vendor/bin/phpunit
  - vendor/bin/phpunit testsdb/PdoMySqlTest.php
  - vendor/bin/phpunit testsdb/PdoPostgresTest.php
#  - vendor/bin/phpunit testsdb/PdoDblibTest.php
