language: php
php:
  - "7.3"
  - "7.2"
  - "7.1"
  - "7.0"
  - "5.6"


services:
  - docker

before_install:
  - sudo service mysql stop || echo "mysql not stopped"
  - sudo service postgresql stop || echo "postgresql not stopped"
  - docker-compose up -d mssql postgres mysql

install:
  - php -i
  - php -m
  - composer install

script: 
  - vendor/bin/phpunit
  - ./wait-for-db.sh mysql && vendor/bin/phpunit testsdb/PdoMySqlTest.php
  - ./wait-for-db.sh postgres && vendor/bin/phpunit testsdb/PdoPostgresTest.php
#  - ./wait-for-db.sh mssql && vendor/bin/phpunit testsdb/PdoDblibTest.php
